#!/bin/sh

#set lan ip
uci set network.lan.ipaddr='192.168.8.1'
uci commit network

#enable wlan
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-device[1].disabled='0'
uci set wireless.@wifi-iface[1].disabled='0'
uci set wireless.@wifi-device[0].country='US'
uci set wireless.@wifi-device[0].channel='auto'
uci set wireless.@wifi-iface[0].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].ieee80211r='1'
uci set wireless.@wifi-iface[0].mobility_domain='1111'
uci set wireless.@wifi-iface[0].reassociation_deadline='20000'
uci set wireless.@wifi-iface[0].ft_over_ds='0'
uci set wireless.@wifi-iface[0].ft_psk_generate_local='1'
uci set wireless.@wifi-iface[0].ieee80211w='1'
uci set wireless.@wifi-iface[0].dtim_period='3'
uci set wireless.@wifi-iface[0].ssid='ImmortalWrt'
uci set wireless.@wifi-device[1].country='US'
uci set wireless.@wifi-device[1].channel='auto'
uci set wireless.@wifi-device[1].htmode='HE160'
uci set wireless.@wifi-iface[1].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[1].key='12345678'
uci set wireless.@wifi-iface[1].ieee80211r='1'
uci set wireless.@wifi-iface[1].mobility_domain='f143'
uci set wireless.@wifi-iface[1].reassociation_deadline='20000'
uci set wireless.@wifi-iface[1].ft_over_ds='0'
uci set wireless.@wifi-iface[1].ft_psk_generate_local='1'
uci set wireless.@wifi-iface[1].ieee80211w='1'
uci set wireless.@wifi-iface[1].dtim_period='3'
uci set wireless.@wifi-iface[1].ssid='ImmortalWrt_5G'
uci set wireless.@wifi-device[1].he_bss_color='8'
uci set wireless.@wifi-device[1].he_su_beamformee='1'
uci commit wireless

#set upnpd
uci set upnpd.config.enabled='1'
uci commit upnpd

exit 0
