#!/bin/sh

#set lan ip
uci set network.lan.ipaddr='192.168.31.1'
uci commit network

#enable wlan
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].disabled='0'
uci set wireless.@wifi-device[1].disabled='0'
uci set wireless.@wifi-iface[1].disabled='0'
uci set wireless.@wifi-device[0].country='US'
uci set wireless.@wifi-device[0].channel='auto'
uci set wireless.@wifi-iface[0].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[0].key='12345678'
uci set wireless.@wifi-iface[0].ssid='OpenWrt'
uci set wireless.@wifi-device[1].country='US'
uci set wireless.@wifi-device[1].channel='auto'
uci set wireless.@wifi-iface[1].encryption='psk2+ccmp'
uci set wireless.@wifi-iface[1].key='12345678'
uci set wireless.@wifi-iface[1].ssid='OpenWrt_5G'
uci commit wireless

#set upnpd
uci set upnpd.config.enabled='1'
uci commit upnpd

exit 0
